[package]
name = "lm-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
lm-app = { path = "../lm-app" }
lm-graphics = { path = "../lm-graphics" }
lm-level = { path = "../lm-level" }
lm-overworld = { path = "../lm-overworld" }
lm-project = { path = "../lm-project" }
lm-profile = { path = "../lm-profile" }
lm-render = { path = "../lm-render" }
lm-rom = { path = "../lm-rom" }
lm-title = { path = "../lm-title" }
rfd = "0.15"

[dev-dependencies]
lm-profile = { path = "../lm-profile", features = ["test-support"] }
lm-rats = { path = "../lm-rats" }

[lints]
workspace = true
